INSERT INTO USER_GROUP
    (`GROUP_NAME`, `GROUP_NICK_NAME`)
VALUES 
    ('HOME1', 'HOME1_NICK');
INSERT INTO USER_GROUP
    (`GROUP_NAME`, `GROUP_NICK_NAME`)
VALUES
    ('HOME2', 'HOME2_NICK');
INSERT INTO USER_GROUP
    (`GROUP_NAME`, `GROUP_NICK_NAME`)
VALUES
    ('HOME3', 'HOME3_NICK');

INSERT INTO `USER`
    (`LOGIN_ID`, `PASSWORD`, `USER_GROUP_ID`)
VALUES
    ('USER1', '1234', 1);
INSERT INTO `USER`
    (`LOGIN_ID`, `PASSWORD`, `USER_GROUP_ID`)
VALUES
    ('USER2', '1234', 2);
INSERT INTO `USER`
    (`LOGIN_ID`, `PASSWORD`, `USER_GROUP_ID`)
VALUES
    ('USER3', '1234', 3);
INSERT INTO `USER`
    (`LOGIN_ID`, `PASSWORD`, `USER_GROUP_ID`)
VALUES
    ('USER4', '1234', 1);
INSERT INTO `USER`
    (`LOGIN_ID`, `PASSWORD`, `USER_GROUP_ID`)
VALUES
    ('USER5', '1234', 2);


INSERT INTO USER_INFO
    (`USER_ID`, `NAME`, `NICK_NAME`, `EMAIL`, `GENDER`)
VALUES
    (1, 'HONG', 'HONG_NICK', 'email@email.com', 'F');
INSERT INTO USER_INFO
    (`USER_ID`, `NAME`, `NICK_NAME`, `EMAIL`, `GENDER`)
VALUES
    (2, 'KIM', 'KIM_NICK', 'email1@email.com', 'M');
INSERT INTO USER_INFO
    (`USER_ID`, `NAME`, `NICK_NAME`, `EMAIL`, `GENDER`)
VALUES
    (3, 'SONG', 'SONG_NICK', 'email2@email.com', 'F');
INSERT INTO USER_INFO
    (`USER_ID`, `NAME`, `NICK_NAME`, `EMAIL`, `GENDER`)
VALUES
    (4, 'LONG', 'LONG_NICK', 'email3@email.com', 'M');
INSERT INTO USER_INFO
    (`USER_ID`, `NAME`, `NICK_NAME`, `EMAIL`, `GENDER`)
VALUES
    (5, 'LONG', 'LONG_NICK1', 'email4@email.com', 'F');
