CREATE TABLE IF NOT EXISTS user (
  `id` INTEGER PRIMARY KEY AUTO_INCREMENT,
  `login_id` VARCHAR(100) NOT NULL,
  `password` VARCHAR(100) NOT NULL,
  `user_group_id` INTEGER DEFAULT NULL,
  UNIQUE KEY USER_UNIQUE_LOGIN_ID (login_id)
);

CREATE TABLE IF NOT EXISTS user_group (
  `id` INTEGER PRIMARY KEY AUTO_INCREMENT,
  `group_name` VARCHAR(100) NOT NULL,
  `group_nick_name` VARCHAR(100) NOT NULL
);

CREATE TABLE IF NOT EXISTS user_info (
  `id` INTEGER PRIMARY KEY AUTO_INCREMENT,
  `user_id` INT NOT NULL,
  `name` VARCHAR(100) NOT NULL,
  `nick_name` VARCHAR(100) NOT NULL, 
  `email` VARCHAR(50) NOT NULL,
  `gender` CHAR(1) DEFAULT NULL,
  UNIQUE KEY USER_INFO_UNIQUE_USER_ID (`user_id`),
  UNIQUE KEY USER_INFO_UNIQUE_NICK_NAME (nick_name),
  UNIQUE KEY USER_INFO_UNIQUE_EMAIL (email)
);