server:
    port: 8002

spring:
  datasource:
    url: jdbc:mariadb://192.168.99.100:3306/test
    driver-class-name: org.mariadb.jdbc.Driver
    username: root
    password: 1234
  
mybatis:
  configuration:
    map-underscore-to-camel-case: true
  mapper-locations:
  - mapper/**/*.xml
  type-aliases-package: io.my.demo.entity
