# server:
#     port: 8002

# spring:
#   datasource:
#     url: jdbc:mariadb://192.168.99.100:3306/test
#     driver-class-name: org.mariadb.jdbc.Driver
#     username: root
#     password: 1234
# mybatis:
#   configuration:
#     map-underscore-to-camel-case: true
#   mapper-locations:
#   - mapper/**/*.xml
#   type-aliases-package: io.my.demo.entity
server:
    port: 8002

spring:
  datasource:
    url: jdbc:h2:mem:testdb
    driver-class-name: org.h2.Driver
    username: sa
    password: 
  
mybatis:
  configuration:
    map-underscore-to-camel-case: true
